# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    _defaults:
        autowire: true
    #service_name:
    #    class: AppBundle\Directory\ClassName
    #    arguments: ['@another_service_name', 'plain_value', '%parameter_name%']

    twig.extension.intl:
        class: Twig_Extensions_Extension_Intl
        tags:
            - { name: twig.extension }

    numo.file_uploader:
        class: NumoBundle\Services\UserUploader
        arguments: ['%upload_directory%']

    numo.doctrine_user_listener:
        class: NumoBundle\EventListener\UserUploadListener
        arguments: ['@numo.file_uploader']
        tags:
            - { name: doctrine.event_listener, event: prePersist }
            - { name: doctrine.event_listener, event: preUpdate }
            - { name: doctrine.event_listener, event: postLoad }
            - { name: doctrine.event_listener, event: preRemove }